/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    sider: Sider;
    nyheter: Nyheter;
    aktiviteter: Aktiviteter;
    grupper: Grupper;
    oppgaver: Oppgaver;
    tildelinger: Tildelinger;
    gruppemeldinger: Gruppemeldinger;
    oppmoter: Oppmoter;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sider: SiderSelect<false> | SiderSelect<true>;
    nyheter: NyheterSelect<false> | NyheterSelect<true>;
    aktiviteter: AktiviteterSelect<false> | AktiviteterSelect<true>;
    grupper: GrupperSelect<false> | GrupperSelect<true>;
    oppgaver: OppgaverSelect<false> | OppgaverSelect<true>;
    tildelinger: TildelingerSelect<false> | TildelingerSelect<true>;
    gruppemeldinger: GruppemeldingerSelect<false> | GruppemeldingerSelect<true>;
    oppmoter: OppmoterSelect<false> | OppmoterSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    forsideinnstillinger: Forsideinnstillinger;
  };
  globalsSelect: {
    forsideinnstillinger: ForsideinnstillingerSelect<false> | ForsideinnstillingerSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  navn: string;
  /**
   * Tilsvarer Person.globalRole i Menighetsplan-appen. Om noen er gruppeleder styres av Grupper.ledere/varaledere, ikke av et felt her.
   */
  globalRolle: 'member' | 'admin';
  telefon?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sider".
 */
export interface Sider {
  id: number;
  tittel: string;
  /**
   * Brukes i URL-en, f.eks. "om-oss".
   */
  slug: string;
  visIMeny?: boolean | null;
  rekkefolge?: number | null;
  /**
   * Valgfritt: velg en annen side som denne skal vises som undermeny-punkt under.
   */
  foreldreside?: (number | null) | Sider;
  /**
   * Beregnes automatisk, kun til visning i sidelisten.
   */
  hierarki?: string | null;
  /**
   * Beregnes automatisk ut fra rekkefølge og foreldreside, brukes kun til å sortere sidelisten. Merk: hvis foreldresidens egen rekkefølge endres senere, må undersidene lagres på nytt for at sorteringen skal oppdateres.
   */
  sorteringsnokkel?: string | null;
  blokker?:
    | (
        | {
            innhold?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tekst';
          }
        | {
            bilde: number | Media;
            bildetekst?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bilde';
          }
        | {
            /**
             * Må starte med https://www.facebook.com/ eller https://facebook.com/
             */
            url: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'facebook';
          }
        | {
            /**
             * YouTube- eller Vimeo-lenke
             */
            url: string;
            bildetekst?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            bilde: number | Media;
            overskrift: string;
            knappTekst?: string | null;
            knappLenke?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            tittel?: string | null;
            antall?: number | null;
            kunGudstjenester?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kalender';
          }
        | {
            kolonner?:
              | {
                  overskrift?: string | null;
                  bilde?: (number | null) | Media;
                  innhold?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kolonner';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nyheter".
 */
export interface Nyheter {
  id: number;
  tittel: string;
  /**
   * Brukes i URL-en, f.eks. "menighetsskolen-modul-3".
   */
  slug: string;
  bilde?: (number | null) | Media;
  /**
   * Kort tekst som vises på forsiden sammen med bildet.
   */
  ingress?: string | null;
  innhold?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publisertDato?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aktiviteter".
 */
export interface Aktiviteter {
  id: number;
  gruppe: number | Grupper;
  tittel: string;
  /**
   * Vises i arrangementslisten på forsiden, i kalenderen og på arrangementets egen side.
   */
  bilde: number | Media;
  start: string;
  slutt?: string | null;
  sted?: string | null;
  type?: ('arrangement' | 'gruppesamling') | null;
  tema?: string | null;
  bibeltekst?: string | null;
  program?:
    | {
        klokkeslett: string;
        tittel: string;
        beskrivelse?: string | null;
        oppgave?: (number | null) | Oppgaver;
        id?: string | null;
      }[]
    | null;
  vert?: (number | null) | User;
  invitasjonSendt?: boolean | null;
  invitasjonSendtDato?: string | null;
  /**
   * Tilsvarer Gathering.isPublic — vises på den offentlige nettsiden når huket av.
   */
  offentlig?: boolean | null;
  erGudstjeneste?: boolean | null;
  avlyst?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grupper".
 */
export interface Grupper {
  id: number;
  navn: string;
  kategori?: ('tjenestegruppe' | 'husgruppe' | 'strategigruppe' | 'ledergruppe') | null;
  medlemmer?: (number | User)[] | null;
  /**
   * Tilsvarer Group.leaderIds — vises som "Leder"/"Hovedleder" på Min side.
   */
  ledere?: (number | User)[] | null;
  /**
   * Tilsvarer Group.deputyLeaderIds — vises som "Nestleder" på Min side.
   */
  varaledere?: (number | User)[] | null;
  moteplan?: {
    ukedag?: ('Mandag' | 'Tirsdag' | 'Onsdag' | 'Torsdag' | 'Fredag' | 'Lørdag' | 'Søndag') | null;
    klokkeslett?: string | null;
    frekvens?: ('hver uke' | 'annenhver uke' | 'hver måned') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oppgaver".
 */
export interface Oppgaver {
  id: number;
  aktivitet: number | Aktiviteter;
  gruppe: number | Grupper;
  tittel: string;
  beskrivelse?: string | null;
  instruksjon?: string | null;
  status?: ('open' | 'assigned' | 'confirmed' | 'vacant' | 'cancelled') | null;
  /**
   * Tilsvarer Task.neededCount
   */
  antallTrengs?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tildelinger".
 */
export interface Tildelinger {
  id: number;
  oppgave: number | Oppgaver;
  person: number | User;
  svar?: ('pending' | 'confirmed' | 'declined' | 'withdrawn') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gruppemeldinger".
 */
export interface Gruppemeldinger {
  id: number;
  gruppe: number | Grupper;
  avsender: number | User;
  innhold: string;
  bilde?: (number | null) | Media;
  /**
   * Systemmeldinger skrives automatisk når noen tar en oppgave, melder forfall osv.
   */
  type?: ('melding' | 'system') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oppmoter".
 */
export interface Oppmoter {
  id: number;
  aktivitet: number | Aktiviteter;
  person: number | User;
  status: 'attending' | 'declined';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sider';
        value: number | Sider;
      } | null)
    | ({
        relationTo: 'nyheter';
        value: number | Nyheter;
      } | null)
    | ({
        relationTo: 'aktiviteter';
        value: number | Aktiviteter;
      } | null)
    | ({
        relationTo: 'grupper';
        value: number | Grupper;
      } | null)
    | ({
        relationTo: 'oppgaver';
        value: number | Oppgaver;
      } | null)
    | ({
        relationTo: 'tildelinger';
        value: number | Tildelinger;
      } | null)
    | ({
        relationTo: 'gruppemeldinger';
        value: number | Gruppemeldinger;
      } | null)
    | ({
        relationTo: 'oppmoter';
        value: number | Oppmoter;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  navn?: T;
  globalRolle?: T;
  telefon?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sider_select".
 */
export interface SiderSelect<T extends boolean = true> {
  tittel?: T;
  slug?: T;
  visIMeny?: T;
  rekkefolge?: T;
  foreldreside?: T;
  hierarki?: T;
  sorteringsnokkel?: T;
  blokker?:
    | T
    | {
        tekst?:
          | T
          | {
              innhold?: T;
              id?: T;
              blockName?: T;
            };
        bilde?:
          | T
          | {
              bilde?: T;
              bildetekst?: T;
              id?: T;
              blockName?: T;
            };
        facebook?:
          | T
          | {
              url?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              url?: T;
              bildetekst?: T;
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              bilde?: T;
              overskrift?: T;
              knappTekst?: T;
              knappLenke?: T;
              id?: T;
              blockName?: T;
            };
        kalender?:
          | T
          | {
              tittel?: T;
              antall?: T;
              kunGudstjenester?: T;
              id?: T;
              blockName?: T;
            };
        kolonner?:
          | T
          | {
              kolonner?:
                | T
                | {
                    overskrift?: T;
                    bilde?: T;
                    innhold?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nyheter_select".
 */
export interface NyheterSelect<T extends boolean = true> {
  tittel?: T;
  slug?: T;
  bilde?: T;
  ingress?: T;
  innhold?: T;
  publisertDato?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aktiviteter_select".
 */
export interface AktiviteterSelect<T extends boolean = true> {
  gruppe?: T;
  tittel?: T;
  bilde?: T;
  start?: T;
  slutt?: T;
  sted?: T;
  type?: T;
  tema?: T;
  bibeltekst?: T;
  program?:
    | T
    | {
        klokkeslett?: T;
        tittel?: T;
        beskrivelse?: T;
        oppgave?: T;
        id?: T;
      };
  vert?: T;
  invitasjonSendt?: T;
  invitasjonSendtDato?: T;
  offentlig?: T;
  erGudstjeneste?: T;
  avlyst?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grupper_select".
 */
export interface GrupperSelect<T extends boolean = true> {
  navn?: T;
  kategori?: T;
  medlemmer?: T;
  ledere?: T;
  varaledere?: T;
  moteplan?:
    | T
    | {
        ukedag?: T;
        klokkeslett?: T;
        frekvens?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oppgaver_select".
 */
export interface OppgaverSelect<T extends boolean = true> {
  aktivitet?: T;
  gruppe?: T;
  tittel?: T;
  beskrivelse?: T;
  instruksjon?: T;
  status?: T;
  antallTrengs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tildelinger_select".
 */
export interface TildelingerSelect<T extends boolean = true> {
  oppgave?: T;
  person?: T;
  svar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gruppemeldinger_select".
 */
export interface GruppemeldingerSelect<T extends boolean = true> {
  gruppe?: T;
  avsender?: T;
  innhold?: T;
  bilde?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oppmoter_select".
 */
export interface OppmoterSelect<T extends boolean = true> {
  aktivitet?: T;
  person?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forsideinnstillinger".
 */
export interface Forsideinnstillinger {
  id: number;
  /**
   * Bakgrunnsbilde for hero-seksjonen øverst på forsiden.
   */
  heroBilde?: (number | null) | Media;
  heroOverskrift?: string | null;
  heroKnappTekst?: string | null;
  heroKnappLenke?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forsideinnstillinger_select".
 */
export interface ForsideinnstillingerSelect<T extends boolean = true> {
  heroBilde?: T;
  heroOverskrift?: T;
  heroKnappTekst?: T;
  heroKnappLenke?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}